from datetime import date, datetime
from typing import Dict, List, Type

from llm_server import util
from llm_server.models.base_model import Model
from llm_server.models.validation_error import ValidationError


class HTTPValidationError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, detail: List[ValidationError] = None):
        """HTTPValidationError - a model defined in OpenAPI

        :param detail: The detail of this HTTPValidationError.
        """
        self.openapi_types = {"detail": List[ValidationError]}

        self.attribute_map = {"detail": "detail"}

        self._detail = detail

    @classmethod
    def from_dict(cls, dikt: dict) -> "HTTPValidationError":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The HTTPValidationError of this HTTPValidationError.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self):
        """Gets the detail of this HTTPValidationError.


        :return: The detail of this HTTPValidationError.
        :rtype: List[ValidationError]
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this HTTPValidationError.


        :param detail: The detail of this HTTPValidationError.
        :type detail: List[ValidationError]
        """

        self._detail = detail
