from datetime import date, datetime
from typing import Dict, List, Type

from llm_server import util
from llm_server.models.base_model import Model


class ValidationErrorLocInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):
        """ValidationErrorLocInner - a model defined in OpenAPI"""
        self.openapi_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt: dict) -> "ValidationErrorLocInner":
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ValidationError_loc_inner of this ValidationErrorLocInner.
        """
        return util.deserialize_model(dikt, cls)
