/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MovieReview,
  MovieSummary,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MovieReviewFromJSON,
    MovieReviewToJSON,
    MovieSummaryFromJSON,
    MovieSummaryToJSON,
} from '../models/index';

export interface MovieSummaryMovieSummaryPostRequest {
    movieReview: MovieReview;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Movie Summary
     */
    async movieSummaryMovieSummaryPostRaw(requestParameters: MovieSummaryMovieSummaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MovieSummary>> {
        if (requestParameters['movieReview'] == null) {
            throw new runtime.RequiredError(
                'movieReview',
                'Required parameter "movieReview" was null or undefined when calling movieSummaryMovieSummaryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/movie_summary`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MovieReviewToJSON(requestParameters['movieReview']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MovieSummaryFromJSON(jsonValue));
    }

    /**
     * Movie Summary
     */
    async movieSummaryMovieSummaryPost(requestParameters: MovieSummaryMovieSummaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MovieSummary> {
        const response = await this.movieSummaryMovieSummaryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
