/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieReview
 */
export interface MovieReview {
    /**
     * 
     * @type {string}
     * @memberof MovieReview
     */
    review: string;
    /**
     * 
     * @type {string}
     * @memberof MovieReview
     */
    reviewer: string;
}

/**
 * Check if a given object implements the MovieReview interface.
 */
export function instanceOfMovieReview(value: object): value is MovieReview {
    if (!('review' in value) || value['review'] === undefined) return false;
    if (!('reviewer' in value) || value['reviewer'] === undefined) return false;
    return true;
}

export function MovieReviewFromJSON(json: any): MovieReview {
    return MovieReviewFromJSONTyped(json, false);
}

export function MovieReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieReview {
    if (json == null) {
        return json;
    }
    return {
        
        'review': json['review'],
        'reviewer': json['reviewer'],
    };
}

export function MovieReviewToJSON(value?: MovieReview | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'review': value['review'],
        'reviewer': value['reviewer'],
    };
}

