/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieSummary
 */
export interface MovieSummary {
    /**
     * 
     * @type {string}
     * @memberof MovieSummary
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MovieSummary
     */
    summary: string;
    /**
     * 
     * @type {number}
     * @memberof MovieSummary
     */
    grade: number;
    /**
     * 
     * @type {string}
     * @memberof MovieSummary
     */
    reviewer: string;
}

/**
 * Check if a given object implements the MovieSummary interface.
 */
export function instanceOfMovieSummary(value: object): value is MovieSummary {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('grade' in value) || value['grade'] === undefined) return false;
    if (!('reviewer' in value) || value['reviewer'] === undefined) return false;
    return true;
}

export function MovieSummaryFromJSON(json: any): MovieSummary {
    return MovieSummaryFromJSONTyped(json, false);
}

export function MovieSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'summary': json['summary'],
        'grade': json['grade'],
        'reviewer': json['reviewer'],
    };
}

export function MovieSummaryToJSON(value?: MovieSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'summary': value['summary'],
        'grade': value['grade'],
        'reviewer': value['reviewer'],
    };
}

